Repository gb-converter/web-site, pull requests merged in 2020-11, with the labels that each got.

#1 Create project tree skeleton.
  .gitignore
  requirements.txt
  website/manage.py
  website/website/__init__.py
  website/website/asgi.py
  website/website/settings.py
  website/website/urls.py
  website/website/wsgi.py
Labels: good first issue

#11 Update ci / cd with collecting new static content before restarting application server
  .github/workflows/django.yml
  requirements.txt
Labels: enhancement

#13 update .gitignore
  .gitignore
Labels: enhancement

#17 Update django.yml
  .github/workflows/django.yml
Labels: enhancement

#18 Use currencies in drop down list instead of countries
  website/converter_frontend/templates/about.html
  website/converter_frontend/templates/contacts.html
  website/converter_frontend/templates/converter.html
  website/converter_frontend/templates/index.html
  website/converter_frontend/views.py
  website/website/urls.py
Labels: bug, enhancement

#27 Fix for issue #23
  website/converter_frontend/views.py
Labels: bug
