Repository gb-converter/web-site, pull requests merged in 2020-12, with the labels that each got.

#33 Update models.py according to notices in issue #23
  website/converter_frontend/migrations/0002_auto_20201201_2206.py
  website/converter_frontend/models.py
Labels: invalid

#48 Closes #46 Zero division bug removed
  website/converter_frontend/static/converter_frontend/css/index.css
  website/converter_frontend/views.py
Labels: bug

#53 Add env variables for deployment step
  .github/workflows/django.yml
Labels: enhancement
